#Characters
image male = "images/Characters/male.png"
image female = "images/Characters/female.png"
image mother = "images/Characters/mother.png"
image principal = "images/Characters/principal.png"
image principalTable = "images/Characters/principalTable.png"
image madProf = "images/Characters/profAngry.png"
image happyM = "images/Characters/profHappy.png"
image happyF = "images/Characters/profHappyF.png"
image profTablet = "images/Characters/profTablet.png"
image profWeab = "images/Characters/profWeab.png"
#Background
image bedroomMale = "images/Background/bedroomMale.jpg"
image diningRoom = "images/Background/diningRoom.jpg"
image travel = "images/Background/travel.jpg"
image canteen = "images/Background/stiCanteen.jpg"
image field = "images/Background/stiField.jpg"
image lab = "images/Background/stiLab.png"
image lib = "images/Background/stiLibrary.jpg"
image libStud = "images/Background/stiLibraryStudents.jpg"
image lobby = "images/Background/stiLobby.jpg"
image outside = "images/Background/stiOutside.jpg"
image room = "images/Background/stiRoom.jpg"
image restroom outside = "images/Background/restroom.png"
image room outside = "images/Background/room.png"
